version: "3.9"
services:
  python-app:
    build:
      context: ./citire
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - mynetwork
    volumes:
      - ./citire:/app/citire
    restart: "no"

networks:
  mynetwork:
    external: true  # Utilizează rețeaua deja creată în primul docker-compose
